### ISSUE TITLE
It is preferable to avoid fixed text sizes.

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#1]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CustomCell.swift#L25

It is preferable to use system sizes so that it is possible to use system settings

**Comment by mrdizlike** [comment]
Fixed
`label.font = UIFont.preferredFont(forTextStyle: .subheadline)`
