### ISSUE TITLE
Do not mix models and views.

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#2]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CustomCell.swift#L86-L94

The description of the model should be removed from the description of this view, in a separate file, since it has no representation to it.

**Comment by mrdizlike** [comment]
Fixed, now it's a separate file
