### ISSUE TITLE
Use contentView.layoutMarginsGuide

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#3]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CustomCell.swift#L42-L62

It is worth placing margins considering the standard margins of the cell content.

**Comment by mrdizlike** [comment]
Fixed, the code now takes into account the standard cell fields.
