### ISSUE TITLE
The possibility of incorrect use of an internal object.

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#4]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CertificateParser/CertificateParser.swift#L212C13-L212C33

A potential error that will cause the application to crash if the ViewController property is not specified. It is possible to use the CertificateParser outside the module since it is public.

**Comment by mrdizlike** [comment]
Fixed, now CertificateParser non-public
