### ISSUE TITLE
Localization capability

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#5]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CertificateParser/CertificateParser.swift#L219-L220
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CertificateParser/CertificateParser.swift#L186-L192
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/Views/ViewCertificateDetails.swift#L53-L92

Add localization capability in the client application.

**Comment by mrdizlike** [comment]
Fixed, now package have localization capability
