### ISSUE TITLE
Processing a long request

### ISSUE THREAD

**Issue by ayuzhin** [mrdizlike/certificate-checker-package#6]
https://github.com/mrdizlike/certificate-checker-package/blob/74db1dbbf1f45317aabce41be55f32c7a371aa71/Sources/certificate-checker-package/CertificateParser/CertificateParser.swift#L17-L21

It is necessary to demonstrate the process of processing a long request. For example, through the activity indicator.

**Comment by mrdizlike** [comment]
Fixed, now an indicator is displayed during the request.
